### ISSUE TITLE
Invalid module found. 

### ISSUE THREAD

**Issue by carvinlo** [piral-samples/piral-microfrontend-demo#10]
When using lazy loading components with `piral-cli-webpack`, something went wrong during runtime.

upgrade the latest version and use piral-cli-webpack@0.5.2
![image](https://user-images.githubusercontent.com/5674761/82113606-ed8d5e00-9789-11ea-9dbf-b872fc5c4ce7.png)
Lazy loading code:
![image](https://user-images.githubusercontent.com/5674761/82113721-be2b2100-978a-11ea-9c22-6f81a92d03f6.png)
And the [diff](https://github.com/carvinlo/piral-microfrontend-demo/commit/041b9f7f8bb41c8db5678cfafb9d88537409e1e4).

**Comment by FlorianRappl** [comment]
I'll have a look!

**Comment by FlorianRappl** [comment]
Fixed in `piral-cli-webpack` 0.5.3. I've updated the `webpack` branch!
