### ISSUE TITLE
There is a short "Error: not_found` transition screen

### ISSUE THREAD

**Issue by carvinlo** [piral-samples/piral-microfrontend-demo#11]
![image](https://user-images.githubusercontent.com/5674761/83415443-a5409200-a451-11ea-9eda-95d9d1153d50.png)
It seems to be because of the asynchronous problem. Is it adjusted to the following to fix this problem?
![image](https://user-images.githubusercontent.com/5674761/83415954-8b537f00-a452-11ea-875b-9217df90cc2a.png)

Here is just an example, you may have a better solution, in the logic of controlling the loading of the pilet.

**Comment by FlorianRappl** [comment]
Yeah I think this is rather a problem with the state container and the loading logic.

Not sure yet if its more or less isolated here (since we don't have any other meaningful page) or if its more generic. If it is, then I think the standard loading strategy should take 1 additional cycle.

I'll come back on this one!

**Comment by FlorianRappl** [comment]
We shipped a fix in the `pre` version. Should be on NPM in the next 10-15 minutes.

**Comment by FlorianRappl** [comment]
Thanks for noticing that. Its a very tiny thing, but unwanted and definitely worth improving.

For the background: We initially did not have this (we went right into loading), but for SSR its important to start from the other direction (i.e., with the assumption everything is "there" and nothing needs to be loaded).

The fix: We now distinguish here (like on other locations) between SSR and CSR. In CSR we start with loading `true`, as we definitely will run through the lifecycle (even if its just "its already loaded").

The SSR part, however, may already return the full thing serving non-JS + more. Its a sensible default, which can, of course, be overridden (i.e., if its known that everything is there then the store may be initialized with loading being `false`).

**Comment by carvinlo** [comment]
The error page transition screen has been fixed. Awesome ！🎉
At the same time, through your explanation, I have a deeper understanding of the loading logic, thank you!
