### ISSUE TITLE
Need to support the new `integrity` feature

### ISSUE THREAD

**Issue by carvinlo** [piral-samples/piral-microfrontend-demo#12]
On the webpack branch, something went wrong:
![image](https://user-images.githubusercontent.com/5674761/83521925-7e966000-a512-11ea-89db-e45c31c79a26.png)

**Comment by FlorianRappl** [comment]
Have you updated to the latest (preview) version of Piral?

There is a fix for this out.

(Note: The fix is to set the `crossOrigin = 'anonymous'`)

**Comment by carvinlo** [comment]
Tried to use the latest version piral-cli@0.11.6-pre.1324, but an error occurred while building the app-shell:
![image](https://user-images.githubusercontent.com/5674761/83528658-f87f1700-a51b-11ea-91c6-a36084976a70.png)

**Comment by FlorianRappl** [comment]
Only update `piral-core`. The webpack plugin is not yet compatible with `piral-cli` 0.11.6 pre.

**Comment by carvinlo** [comment]
OK👌
