### ISSUE TITLE
UnhandledPromiseRejectionWarning on run

### ISSUE THREAD

**Issue by jdevoo** [piral-samples/piral-microfrontend-demo#22]
Hello, I am hitting an UnhandledPromiseRejectionWarning with run.
```
Error: ENOENT: no such file or directory, lstat '/home/jdevoo/playground/piral-microfrontend-demo/team-blue/node_modules/react-dom/unstable-fizz.browser.js'
```
Here's what I see when I grep react-dom in package-lock.json
```
    "@types/react-dom": {
      "resolved": "https://registry.npmjs.org/@types/react-dom/-/react-dom-16.9.9.tgz",
    "react-dom": {
      "resolved": "https://registry.npmjs.org/react-dom/-/react-dom-17.0.1.tgz",
```
The 16.9.9 has no unstable-fizz.browser.js in the directory as indicated by the warning.
Any ideas how I can get past this?

**Comment by FlorianRappl** [comment]
Thanks for reporting this issue. I'll have a look into it!

**Comment by FlorianRappl** [comment]
Yeah its an issue in `parcel-plugin-externals` (actually solved already in the latest version: https://github.com/FlorianRappl/parcel-plugin-externals/issues/24).

I solved it now with:

```sh
echo '' > team-blue/node_modules/react-dom/unstable-fizz.browser.js
echo '' > team-red/node_modules/react-dom/unstable-fizz.browser.js
echo '' > team-green/node_modules/react-dom/unstable-fizz.browser.js
```

This works fine, however, I'll look if I can update dependencies to work without any such hack / modification.

**Comment by FlorianRappl** [comment]
Updated to the last version. Should now work without that modification above.

Just pull, run `install.sh` then `run.sh`. Let me know if further issues exist.

**Comment by jdevoo** [comment]
thank you for fixing this so quickly Florian!
