### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by carvinlo** [piral-samples/piral-microfrontend-demo#9]
upgrade piral-cli@0.11.4 and use piral-cli-webpack@0.5.1 
Something went wrong during runtime，This is my upgraded [package.json](https://github.com/carvinlo/piral-microfrontend-demo/commit/fd06785476fe992af7ca6f29799f5523a8ad9582). 
Did I miss the other configuration?

![image](https://user-images.githubusercontent.com/5674761/81701319-69db2500-949c-11ea-88f3-89c5efb8bee6.png)

**Comment by FlorianRappl** [comment]
This seems to be an error with the sharing of dependencies.

I can take a look here.

**Comment by FlorianRappl** [comment]
Your config is definitely right. These are bugs in the `piral-cli-webpack` plugin.

I've published a fix. Testing.

**Comment by FlorianRappl** [comment]
Seems to be working.

I've also created a [branch using Webpack instead of Parcel](https://github.com/piral-samples/piral-microfrontend-demo/tree/webpack).
